### PR TITLE
19-cleanup-suite

### PR DESCRIPTION
**Pull request by KaranTikellu7**
New Branch created for sorting files into separate folders and removing Invoke browser folder.

### CODE REVIEW

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 
image

**Comment by KaranTikellu7** [comment]
Folders renamed as per instruction

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

The branch has got merge conflicts.  Please rebase your branch with master  and resolve all conflicts.

**Comment by prabhakarbattula** [comment]
Closing this as it is taken care of in https://github.com/prabhakarbattula/aceinvoice-selenium/pull/22

**Pull request closed without merging**
