### PR TITLE
Modified Testcase file

### PR DESCRIPTION
**Pull request by KaranTikellu7**
Changes in Test Case file

### CODE REVIEW

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Please update as informed.

**Comment by KaranTikellu7** [comment]
@prabhakarbattula  Test file modified as per instruction. Please review.

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Please update PR as per video.
https://www.useloom.com/share/34ad9e39d0d94bb48cbbcd06e1982e07

**Comment by KaranTikellu7** [comment]
@prabhakarbattula  Changes Done as per instruction..

**Comment by prabhakarbattula** [comment]
@KaranTikellu7 

Please update PR as per video. https://www.useloom.com/share/91fa1cbded984411bce8ef80bc91e73b

**Pull request merged**
