### PR TITLE
test added for checking required fields on Signup page

### PR DESCRIPTION
**Pull request by iamjayesh02**
added test case

### CODE REVIEW

**Comment by iamjayesh02** [comment]
sure

**Comment by iamjayesh02** [comment]
@prabhakarbattula  modified the test case using first branch.

**Comment by prabhakarbattula** [comment]
@iamjayesh02 

Please update PR as per video.
https://www.useloom.com/share/c268017f2490464fab63874660e07335

**Comment by iamjayesh02** [comment]
@prabhakarbattula  modifications done as per guided by you.

**Comment by prabhakarbattula** [comment]
@iamjayesh02 

In this PR you have added test to verify elements on Signup page and it is not what is expected as part of the issue assigned. You need to write test to verify required fields on Signup page and assert the error messages.
https://www.useloom.com/share/6e9de750c1f04c19bb2b33bad9858bed

**Comment by iamjayesh02** [comment]
@prabhakarbattula Test case updated.

**Pull request merged**
